### ISSUE TITLE
Add option to output transclusion errors with a specified replacement. 

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#259]
Errors in the console are useful when using hercule in a build pipeline, but having visual feedback on the output when transclusion has failed would be great to enable content authors to find out about missing or mispelled target links!

This would mean allowing to fail silently (or error but still provide an output to the callback) and replacing outputs by a specified snippet (which by default could just be text about the missing target).

**Comment by jamesramsay** [comment]
If you have a chance, take a look at some of the refactoring I've done to isolate over the last few weeks and months to decouple the logic which receives the text link and opens the link (local file, http etc) and then returns a stream.

My intention is to open an API for overriding the `resolveLink` function (https://github.com/jamesramsay/hercule/blob/master/src/resolve.js#L51) so that applications like in browser usage can be handled.

This also gives you ability to catch and handle the errors yourself. See: https://github.com/jamesramsay/hercule/tree/master/src/inflaters

For example, you could handle the error and instead of returning a stream containing file contents, you could return a stream that simply returns one object like in `string.js` with an error message to be inserted inline.

Do you think this would be sufficient, at least for now?

With reference to #209, sorry that it's taking so long. I'd hoped to have more time to work on Hercule, and what little time I've had has been primarily directed towards sourcemaps.

**Comment by jmatsushita** [comment]
Hey I've just given a try to the new api in nodejs with a metalsmith module I'm working on and it works great!
