### ISSUE TITLE
[discussion] Support for html strings in JSON

### ISSUE THREAD

**Issue by hellboy81** [jamesramsay/hercule#27]
Is there possible to extract html - String from Body description

+Body 

``` js
{
   field1: 'Value1'
   html: '<HEAD></HEAD><BODY></BODY>'
}
```

I don't need to extract whole body to JSON file, only HTML needed.

**Comment by jamesramsay** [comment]
Do you mean that you'd like to be able to transclude a portion of a JSON file into another file?

How would you imagine this working syntactically?

**Comment by zdne** [comment]
> transclude a portion of a JSON file into another file

not sure if this solves the OP question but rather than transcluding JSONs I would suggest to take look at [MSON](https://github.com/apiaryio/mson) and use it to define and reuse data structures within API Blueprint using [Attributes](https://github.com/apiaryio/api-blueprint/blob/master/examples/09.%20Advanced%20Attributes.md)
