### ISSUE TITLE
Resolver argument source equals "string"

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#375]
Hi there,

I'm working on a metalsmith module that wraps hercule to include it in a metalsmith pipeline and I ran into a problem while trying to use transcludeString with custom resolvers.

I can see that when used in this mode the source argument to the resolver is equal to "string" and I assume that this is also connected to the fact that I have a problem with nested traversals. I guess that in "string" mode the nesting isn't enabled? 

I can try to think of ways to address this, but I wanted first to make sure I understood correctly the current state of affairs.

FYI [this console statement](https://github.com/contentascode/metalsmith-transclude/blob/ba934e404975d37ba9629da87ebbf972476b23ff/src/index.js#L60) outputs `string`. And [this test](https://github.com/contentascode/metalsmith-transclude/tree/ba934e404975d37ba9629da87ebbf972476b23ff/test/fixtures/deep/src) fails [with an error which is linked to the order of transclusion](https://travis-ci.org/contentascode/metalsmith-transclude/jobs/240079834#L238-L242)  which I was hoping hercule would manage :)

Thanks for your time!

Jun

PS: I'll get back to browser base work soon and will comment on #209

**Comment by jmatsushita** [comment]
And by the way, it works if instead of looking up the metalsmith file array, I go back to the files, but I'd rather avoid going back to the file system if I can.

**Comment by jamesramsay** [comment]
Currently strings are treated as fully resolved, see: https://github.com/jamesramsay/hercule/blob/master/src/resolver.js#L35

I'll take a look in more depth over the weekend to see if there might be a simple way to handle this.

**Comment by jamesramsay** [comment]
I unhelpfully linked to the wrong line in my previous comment. I should have linked to https://github.com/jamesramsay/hercule/blob/master/src/resolver.js#L55

The issue is that `resolveMetalsmith` is returning a string. When a string is returned `resolveToReadableStream` treats the content as fully processed. Instead returning a readable stream will cause further processing allows the content of the stream to be further processed for nested transcludes.

From the docs:

> `content` (_Stream | String_): The content to be transcluded. Streams are processed for further transclusion links. Strings are assumed fully processed.

Adjusting `content` in `resolveMetalsmith` to be a stream might be as simple as:

```js

const content = new stream.Readable({ encoding: 'utf8' });
content.push(files[targetingKey].contents.toString());
content.push(null);

```

Hope that helps!

**Comment by jmatsushita** [comment]
Ah excellent, I'll give this a shot soon and let you know how it went!

**Comment by jmatsushita** [comment]
I can confirm that this work, thanks a lot!
