### ISSUE TITLE
Provide placeholder context to resolver

### ISSUE THREAD

**Issue by jmatsushita** [jamesramsay/hercule#389]
Hi there,

Not sure if this is easy but I'd like to be able for my custom resolver to use context metadata passed by the placeholder syntax in order to supply context to the transcluded snippet and use this to display snippet variants or parameterise snippets.

Would it be possible to pass the context to the resolver? 

Let me know if this makes sense!

Jun

**Comment by jamesramsay** [comment]
@jmatsushita have you had a chance to look at #388 this provides the placeholder string as an arg? 

Am I right in understanding you'd like a structured representation of the link in the placeholder including references?

This should be possible, but I'm not sure what the use case would be. The reason being that the references (e.g. `fizz:"buzz"` in `:[foo](bar.md fizz:"buzz")` are scoped to the content of content of `bar.md` rather than resolving `bar.md` to a URL itself.

The resolver function receives a single URL that is selected from the link, fallback and ancestor references, and is only meant to be resolving the URL to an input stream.

I am misunderstanding what you're trying to do?

**Comment by jmatsushita** [comment]
#388 seems to do exactly what I need!

Here's a more detailed example about the use case:

foo.md:
```
I feel :[](bar.md fizz:"buzz")!
```

bar.md:
```
{{fizz}}
```

result:
```
I feel buzz!
```

This implies a templating engine which would be passed as an argument of the `metalsmith-transclude` plugin. 

Given that the resolver function can return the transcluded content, if the user chooses this option I can use the placeholder data as a metadata for a templating engine and return the rendered content.

It feels like it's a superset of how its used with MSON where the `:[is required](required || "optional")` from the [readme](https://github.com/jamesramsay/hercule#default-placeholders), stands for (in [nunjucks](https://mozilla.github.io/nunjucks/templating.html#if-expression)):
```{{ required if required else "optional" }}```, passing ```{ required: "required"}``` as the metadata for the template.

If that's the case maybe `hercule` itself could use this approach to deal with placeholders make templating pluggable? This could be made very general with [JSTransformers](https://github.com/jstransformers/jstransformer) for instance.

But maybe I'm missing something? I'll give a try to the `resolver-placeholder` branch!

**Comment by jamesramsay** [comment]
Interesting application. Let me know how you get on.

Thanks for the link to JSTransformers.
